### ISSUE TITLE
Request.get in 3 endpoints

### ISSUE THREAD

**Issue by piyushc0** [ionadev/image-gen-api#4]
Contrast.js
Invert.js
Sepia.js

**Comment by anishshobithps** [comment]
no u

**Comment by whopiyush** [comment]
# Fixed
 Thanks For Getting that to our attention. We Have Ficed that.
* https://github.com/ionadev/image-gen-api/commit/0162f14f74223e14192231747a97fa243c57a950
* https://github.com/ionadev/image-gen-api/commit/27b440b9276d88885ba96b2f6b8ffc9b5498e1a1
